var keyword="";
var timetype="";
var attributiontype="";
var weekday=0;
$(document).ready(function(){
  $.ajax({
	  type:"POST",
		url:"./activity/activity_search.php",
		data:{
			keyword:keyword,
			timetype:timetype,
			attributiontype:attributiontype,
			weekday:weekday,
			page:0},
		success:function(html){
			$("#main").html(html);
		}
	  });
});
function searchit(){
	  keyword=$('#keyword').val();
	  timetype=$(':checked[name="time_type"]').val(); 
	  attributiontype=$(':checked[name="attribution_type"]').val();
	  weekday=(document.getElementById("weekday_0").checked?64:0)+
					(document.getElementById("weekday_1").checked?32:0)+
					(document.getElementById("weekday_2").checked?16:0)+
					(document.getElementById("weekday_3").checked?8:0)+
					(document.getElementById("weekday_4").checked?4:0)+
					(document.getElementById("weekday_5").checked?2:0)+
					(document.getElementById("weekday_6").checked?1:0);
	$.ajax({
		type:"POST",
		url:"./activity/activity_search.php",
		data:{
			keyword:keyword,
			timetype:timetype,
			attributiontype:attributiontype,
			weekday:weekday,
			page:0},
		success:function(html){
			$("#main").html(html);
		}	
	});
}
function nextpage(){
	$.ajax({
		type:"POST",
		url:"./activity/activity_search.php",
		data:{
			keyword:keyword,
			timetype:timetype,
			attributiontype:attributiontype,
			weekday:weekday,
			page:document.getElementById("current").innerHTML},
		success:function(html){
			$("#main").html(html);
		}
	});	
}
function prepage(){
	//alert((document.getElementById("current").innerHTML-1));
	$.ajax({
	type:"POST",
		url:"./activity/activity_search.php",
		data:{
			keyword:keyword,
			timetype:timetype,
			attributiontype:attributiontype,
			weekday:weekday,
			page:(document.getElementById("current").innerHTML-2)},
		success:function(html){
			$("#main").html(html);
		}
	});
}
function firstpage(){
	$.ajax({
	type:"POST",
		url:"./activity/activity_search.php",
		data:{
			keyword:keyword,
			timetype:timetype,
			attributiontype:attributiontype,
			weekday:weekday,
			page:0},
		success:function(html){
			$("#main").html(html);
		}
	});
}
function lastpage(){
	$.ajax({
	type:"POST",
		url:"./activity/activity_search.php",
		data:{
			keyword:keyword,
			timetype:timetype,
			attributiontype:attributiontype,
			weekday:weekday,
			page:(document.getElementById("last").innerHTML-1)},
		success:function(html){
			$("#main").html(html);
		}
	});
}
